### ISSUE TITLE
IP Torrents search

### ISSUE THREAD

**Issue by scbuckeye75** [binhex/arch-couchpotato#3]
IP Torrents is my search provider, but it never pulls any data.

This is a known issue on the CouchPotatoServer on [GitHub](https://github.com/CouchPotato/CouchPotatoServer/pull/6766/files#diff-853b684a9eccd4e0460dd7c5049b1be3):

I am using the docker in unRaid 6.2.4

**Comment by binhex** [comment]
wont fix
